### ISSUE TITLE
Won't compile or Run due to issues on line 63

### ISSUE THREAD

**Issue by ghost** [Manosgou/Fuzzy-Pi-Fan#1]

**Comment by Manosgou** [comment]
Thank you for the report. I've been a little busy lately, working on a different project. As soon as I get some time, I'll check out the bug.

**Comment by Manosgou** [comment]
Try clonig the latest version and feel to share any problems.

**Comment by Manosgou** [comment]
Try clonig the latest version and feel to share any problems.

**Comment by Manosgou** [comment]
Try cloning the latest version and share any problems.

**Comment by ghost** [comment]
Will try in a bit

**Comment by ghost** [comment]
I get code: 22 kind: Invalid input, message: "Invalid argument"

**Comment by Manosgou** [comment]
Can you access the temperature sensors throw the file system?(/sys/class/thermal/)

**Comment by ghost** [comment]
> Can you access the temperature sensors throw the file system?(/sys/class/thermal/)

Yeah I see thermal_zone0

**Comment by ghost** [comment]
Btw you may want to update readme since bookworm the config is at /boot/firmware/config.txt

**Comment by Manosgou** [comment]
In my case I use an old version of Raspbian. The Boot.txt file is located in the path mentioned in the readme. Perhaps the problem you are experiencing has to do with the latest version of Raspbian.

**Comment by ghost** [comment]
Ah

**Comment by Manosgou** [comment]
I will upgrade Raspbian to the latest version and do some testing.

**Comment by ghost** [comment]
Ok thanks

**Comment by Manosgou** [comment]
The version of the operating system has nothing to do with the problem. An unnecessary check of the PWM signal status may be causing the IO error. Repeat the attempt with the latest version. If it still does not work, try commenting on line 62.

**Comment by ghost** [comment]
I'm not sure if I'm compiling this correctly, could you give me the proper commands

**Comment by Manosgou** [comment]
Inside the cloned directory run the following command:`cargo run`

What makes you think that the code execution is not correct? Is the fan behaving strangely (spinning at maximum, minimum, etc.)?

**Comment by ghost** [comment]
> Inside the cloned directory run the following command:`cargo run`
> 
> What makes you think that the code execution is not correct? Is the fan behaving strangely (spinning at maximum, minimum, etc.)?

the fan doesnt spin at all, i just get errors when trying to mek it work, but ill try this now

**Comment by Manosgou** [comment]
Any improvement?

**Comment by ghost** [comment]
Still the same tbh

**Comment by Manosgou** [comment]
Which GPIO pins do you use?

**Comment by ghost** [comment]
GPIO18 for pwm

**Comment by Manosgou** [comment]
Have you checked GPIO12? Are you supplying the fan with the correct voltage?

**Comment by ghost** [comment]
will check now

**Comment by Manosgou** [comment]
On my setup I use GPIO12(pin 32).

**Comment by ghost** [comment]
Works
